include = "base.toml"

output_dir = "./models/tiny_shakespeare"

[data]
train_fpath = "./data/train-gpt2.bin"
val_fpath = "./data/val-gpt2.bin"
seq_len = 128

[optimization]
decay_steps = 2_500 # should be kept same as max_steps
warmup_steps = 100

[trainer]
accelerator = "auto"
max_steps = 2_500
val_check_interval = 250
limit_val_batches = 200
log_every_n_steps = 10
